import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "@/components/themes-provider";
import KbarProvider from "@/components/kbar";

const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ThemeProvider attribute="class" defaultTheme="dark">
        <html lang="en">
          <TRPCReactProvider>
            <KbarProvider>
              <body className={`${poppins.className} antialiased`}>
                {children}
              </body>
            </KbarProvider>
          </TRPCReactProvider>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
